name: plugin-rs-ci

on:
  plugin_rust_ci:
    inputs:
      working-directory:
        required: true
        type: string

jobs:
  ci:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Read .nvmrc
        run: echo ::set-output name=NVMRC::$(cat .nvmrc)
        id: nvm

      - name: Setup Node.js
        uses: actions/setup-node@master
        with:
          node-version: '${{ steps.nvm.outputs.NVMRC }}'

      - name: Install dependencies
        run: yarn install --nonInteractive --frozen-lockfile --prefer-offline
        working-directory: ${{ inputs.working-directory }}

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true

      - name: Build
        run: cargo build
        working-directory: ${{ inputs.working-directory }}

      - name: Test
        run: cargo test
        working-directory: ${{ inputs.working-directory }}