name: plugin-interface-cd

on:
  workflow_call:
    inputs:
      WORKING_DIRECTORY:
        required: true
        type: string

jobs:
  Publish-Interface:
    if: |
      github.event.pull_request.merged &&
      endsWith(github.event.pull_request.title, '/workflows/cd')
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Read .nvmrc
        run: echo ::set-output name=NVMRC::$(cat .nvmrc)
        id: nvm

      - name: Setup Node.js
        uses: actions/setup-node@master
        with:
          node-version: '${{ steps.nvm.outputs.NVMRC }}'

      - name: Install dependencies
        run: yarn install --nonInteractive --frozen-lockfile --prefer-offline
        working-directory: ${{ inputs.WORKING_DIRECTORY }}

      - name: Build
        run: yarn build
        working-directory: ${{ inputs.WORKING_DIRECTORY }}

      - name: Deploy
        run: yarn deploy
        working-directory: ${{ inputs.WORKING_DIRECTORY }}

      - name: PR New URI
        uses: peter-evans/create-pull-request@v3
        with:
          branch: interface-cd-pr-${{github.event.number}}
          commit-message: "interface: update deployment URI"
          title: "interface: update deployment URI"
          body: "Triggered by: https://github.com/${{github.repository}}/pull/${{github.event.number}}"