name: plugin-interface-ci

on:
  plugin_interface_ci:
    inputs:
      WORKING_DIRECTORY:
        required: true
        type: string

jobs:
  Build-Interface:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Read .nvmrc
        run: echo ::set-output name=NVMRC::$(cat .nvmrc)
        id: nvm

      - name: Setup Node.js
        uses: actions/setup-node@master
        with:
          node-version: '${{ steps.nvm.outputs.NVMRC }}'

      - name: Install dependencies
        run: yarn install --nonInteractive --frozen-lockfile --prefer-offline
        working-directory: ${{ inputs.WORKING_DIRECTORY }}

      - name: Build
        run: yarn build
        working-directory: ${{ inputs.WORKING_DIRECTORY }}