name: plugin-rs-cd

on:
  workflow_call:
    inputs:
      WORKING_DIRECTORY:
        required: true
        type: string

jobs:
  Crate-Publish:
    if: |
      github.event.pull_request.merged &&
      endsWith(github.event.pull_request.title, '/workflows/cd')
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Read .nvmrc
        run: echo ::set-output name=NVMRC::$(cat .nvmrc)
        id: nvm

      - name: Setup Node.js
        uses: actions/setup-node@master
        with:
          node-version: '${{ steps.nvm.outputs.NVMRC }}'

      - name: Install dependencies
        run: yarn install --nonInteractive --frozen-lockfile --prefer-offline
        working-directory: ${{ inputs.WORKING_DIRECTORY }}

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.69.0
          override: true

      - name: Publish
        run: cargo publish --token {{ secrets.POLYWRAP_BUILD_BOT_CRATES_PAT }}
        working-directory: ${{ inputs.WORKING_DIRECTORY }}